import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/providers";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    geistSans.variable,
                    geistMono.variable,
                    "antialiased",
                )}
            >
                <Providers>
                    {/* <Toaster position="top-right" /> */}
                    <div className="font-mono flex flex-col items-center min-h-screen">
                        <Navbar />
                        <div className="container py-8 px-5 w-full flex-1">
                            {children}
                        </div>
                        {/* <Footer /> */}
                    </div>
                </Providers>
            </body>
        </html>
    );
}
